<form method="<?php echo $this->modalData['form']->getMethod()?>" action="<?php echo $this->modalData['form']->getAction()?>" class="<?php echo $this->modalData['form']->getAttrib('class');?>"
      id="modalForm">    
        
    <header style="margin-top:50px">

            <div class="input-control select">
                <?php echo $this->modalData['form']->getElement('tasks'); ?>
            </div>

        <div class="input-control select" style="margin-left: 50px;">
            <?php echo $this->modalData['form']->getElement('id_programmist'); ?>
        </div>

    </header>
    <footer>
        <div class="input-control text datepicker" data-role="datepicker" data-scheme="darcula" data-other-days="true" 
             data-week-start="1">
            <?php echo $this->modalData['form']->getElement('date'); ?>
            <button class="button"><span class="mif-calendar"></span></button>
        </div>
        <div class="input-control modern text iconic">
            <?php echo $this->modalData['form']->getElement('hours'); ?>
            <span class="label">Hours</span>
            <span class="informer">Please enter count of hours</span>
            <span class="placeholder">Hours*</span>
        </div>
    </footer>
    <div class="input-control textarea"
         data-role="input" data-text-auto-resize="true" data-text-max-height="108">
        <?php echo $this->modalData['form']->getElement('note'); ?>
    </div>
    <?php if(isset($this->modalData['id'])){?>
        <input type="hidden" name="id" value="<?php echo $this->modalData['id']; ?>" />
    <?php }?>
</form>