<h1 class="title"><?php echo $this->data['title'];?></h1>
<?php if(!empty($this->data['addButton'])){?>
    <div class="table-options">
        <p>
            <a class="button loading-cube lighten primary" href="<?php echo $this->url(array('controller'=>$this->data['addUrl']['controller'],
                'action'=>$this->data['addUrl']['action']),null,true);?>" ><?php echo $this->data['addButton']; ?></a>
        </p>
    </div>
<?php }?>

<div data-role="dialog" id="dialog" class="padding20 dialog" data-close-button="true" data-windows-style="true" style="left: 0; right: 0; width: auto; height: auto; visibility: hidden; top: 300px;"></div>

<table id="data_table" class="dataTable striped border bordered" data-role="datatable" data-searching="true" role="grid" aria-describedby="data_table_info">
    <thead>
    <tr role="row">
        <?php foreach($this->data['columns'] as $column){?>
            <th class="sorting_desc" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending"><?php echo $column?></th>
        <?php }?>        
    </tr>
    </thead>

    <tfoot>
    <tr role="row">
        <?php foreach($this->data['columns'] as $column){?>
            <th class="sorting_desc" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending"><?php echo $column; ?></th>
        <?php }?>        
    </tr>
    </tfoot>

    <tbody id="table-body">

    <?php
    foreach ($this->data['rows'] as $row){ ?>
        <tr>
            <?php echo $this->partial('in-progress/row.phtml', ['row'=>$row]); ?>
        </tr>
    <?php }?>


    </tbody>
</table>
