<div class="tile-area-controls">
    <a href="<?php echo $this->url(['controller' => 'index', 'action' => 'index']) ?>"
       class="square-button bg-transparent fg-white bg-hover-dark no-border"><span class="mif-home"></span></a>
    <?php if ($this->role == 'admin') { ?>
        <a href="<?php echo $this->url(['controller' => 'users', 'action' => 'index']); ?>"
           class="square-button bg-transparent fg-white bg-hover-dark no-border load-tile-content"><span class="mif-organization"></span></a>
    <?php } ?>
    <button class="image-button icon-right bg-transparent fg-white bg-hover-dark no-border"><span
            class="sub-header no-margin text-light">Anton Ashin</span> <span class="icon mif-user"></span></button>
    <button class="square-button bg-transparent fg-white bg-hover-dark no-border" onclick="showSearch()"><span
            class="mif-search"></span></button>
    <button class="square-button bg-transparent fg-white bg-hover-dark no-border" onclick="showSettings()"><span
            class="mif-cog"></span></button>
    <a href="<?php echo $this->url(['controller' => 'login', 'action' => 'logout']) ?>"
       class="square-button bg-transparent fg-white bg-hover-dark no-border"><span class="mif-switch"></span></a>
</div>